"""NTU-RGB+D 120 action labels in zero-based classifier order."""

NTU_ACTION_LABELS = [
    "drink water",
    "eat meal/snack",
    "brushing teeth",
    "brushing hair",
    "drop",
    "pickup",
    "throw",
    "sitting down",
    "standing up",
    "clapping",
    "reading",
    "writing",
    "tear up paper",
    "wear jacket",
    "take off jacket",
    "wear a shoe",
    "take off a shoe",
    "wear on glasses",
    "take off glasses",
    "put on a hat/cap",
    "take off a hat/cap",
    "cheer up",
    "hand waving",
    "kicking something",
    "reach into pocket",
    "hopping",
    "jump up",
    "make a phone call",
    "playing with phone/tablet",
    "typing on a keyboard",
    "pointing to something with finger",
    "taking a selfie",
    "check time (from watch)",
    "rub two hands together",
    "nod head/bow",
    "shake head",
    "wipe face",
    "salute",
    "put the palms together",
    "cross hands in front (say stop)",
    "sneeze/cough",
    "staggering",
    "falling",
    "touch head (headache)",
    "touch chest (stomachache)",
    "touch back (backache)",
    "touch neck (neckache)",
    "nausea or vomiting condition",
    "use a fan/feeling warm",
    "punching/slapping other person",
    "kicking other person",
    "pushing other person",
    "pat on back of other person",
    "point finger at the other person",
    "hugging other person",
    "giving something to other person",
    "touch other person's pocket",
    "handshaking",
    "walking towards each other",
    "walking apart from each other",
    "put on headphone",
    "take off headphone",
    "shoot at basket",
    "bounce ball",
    "tennis bat swing",
    "juggle table tennis ball",
    "hush",
    "flick hair",
    "thumb up",
    "thumb down",
    "make OK sign",
    "make victory sign",
    "staple book",
    "counting money",
    "cutting nails",
    "cutting paper",
    "snap fingers",
    "open bottle",
    "sniff/smell",
    "squat down",
    "toss a coin",
    "fold paper",
    "ball up paper",
    "play magic cube",
    "apply cream on face",
    "apply cream on hand",
    "put on bag",
    "take off bag",
    "put object into bag",
    "take object out of bag",
    "open a box",
    "move heavy objects",
    "shake fist",
    "throw up cap/hat",
    "capitulate",
    "cross arms",
    "arm circles",
    "arm swings",
    "run on the spot",
    "butt kicks",
    "cross toe touch",
    "side kick",
    "yawn",
    "stretch oneself",
    "blow nose",
    "hit with object",
    "wield knife",
    "knock over",
    "grab stuff",
    "shoot with gun",
    "step on foot",
    "high-five",
    "cheers and drink",
    "carry object",
    "take a photo",
    "follow",
    "whisper",
    "exchange things",
    "support somebody",
    "rock-paper-scissors",
]

if len(NTU_ACTION_LABELS) != 120:
    raise RuntimeError(
        f"Expected 120 NTU-RGB+D action labels, found {len(NTU_ACTION_LABELS)}."
    )
